name: Dispatch to Central DevOps

on:
  push:
    branches:
      - dev

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch Deployment Event to devops-practice
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITPAT }}
          repository: fardin-254/devops-practice
          event-type: portfolio-deploy
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
